# docker build -t wenex/client-backend:latest .
x-common: &common
  image: wenex/client-backend:latest
  env_file:
    - .env
  network_mode: host

services:
  gateway:
    profiles: [gateway, client]
    container_name: client-gateway
    ports:
      - 6010:6010 # Rest
    environment:
      SERVICE_NAME: gateway
    <<: *common

  services:
    profiles: [services, client]
    container_name: client-services
    ports:
      - 7010:7010 # Rest
    environment:
      SERVICE_NAME: services
    <<: *common

  workers:
    profiles: [workers, client]
    container_name: client-workers
    ports:
      - 8010:8010 # Rest
    environment:
      SERVICE_NAME: workers
    <<: *common

  # ---------
  # Commands
  # ---------

  serve-static:
    profiles:
      - serve-static
    entrypoint: ['bash', '-c', 'npm run serve:static']

  platform-clean:
    profiles:
      - platform-clean
    entrypoint: ['bash', '-c', 'npm run platform:clean']
    <<: *common

  platform-seed:
    profiles:
      - platform-seed
    entrypoint: ['bash', '-c', 'npm run platform:seed']
    <<: *common

  platform-raise:
    profiles:
      - platform-raise
    entrypoint: ['bash', '-c', 'npm run platform:raise']
    <<: *common
