version: '3.8'

x-common: &common
  env_file:
    - .env
  networks:
    - client

services:
  #######################
  # CLIENT SERVICES
  #######################
  client:
    build:
      args:
        SERVICE_NAME: gateway
      context: .
    ports:
      - '8000:8000' # REST
    environment:
      NODE_ENV: prod
    <<: *common

  #######################
  # CRAFTS SERVICES
  #######################
  crafts:
    build:
      args:
        SERVICE_NAME: services
      context: .
    ports:
      - '8001:8001' # REST
    environment:
      NODE_ENV: prod
    <<: *common

  #######################
  # WORKER SERVICES
  #######################
  workers:
    container_name: workers
    build:
      args:
        SERVICE_NAME: workers
      context: .
    ports:
      - 8002:8002 # Rest
    environment:
      NODE_ENV: prod
      SENTRY_DSN:
    <<: *common

networks:
  client:
    driver: bridge
