x-common: &common
  env_file:
    - .env
  environment:
    KAFKA_HOST: kafka
    REDIS_HOST: redis
    MINIO_HOST: minio
  networks:
    - localnet

services:
  gateway:
    build:
      args:
        SERVICE_NAME: gateway
      context: .
    ports:
      - 6010:6010 # Rest
    <<: *common

networks:
  localnet:
    driver: bridge
