# docker build -t wenex/client:latest .
x-common: &common
  image: wenex/client:latest
  env_file:
    - .env
  networks:
    - localnet

x-env: &env
  REDIS_HOST: redis
  NATS_SERVERS: nats://nats:4222

services:
  gateway:
    profiles: [gateway, client]
    container_name: client-gateway
    ports:
      - 6010:6010 # Rest
    environment:
      SERVICE_NAME: gateway
      <<: *env
    <<: *common

  services:
    profiles: [services, client]
    container_name: client-services
    ports:
      - 7010:7010 # Rest
    environment:
      SERVICE_NAME: services
      <<: *env
    <<: *common

  workers:
    profiles: [workers, client]
    container_name: client-workers
    ports:
      - 8010:8010 # Rest
    environment:
      SERVICE_NAME: workers
      <<: *env
    <<: *common

  # ---------
  # Commands
  # ---------

  serve-static:
    profiles:
      - serve-static
    entrypoint: ['bash', '-c', 'npm run serve:static']

  platform-clean:
    profiles:
      - platform-clean
    entrypoint: ['bash', '-c', 'npm run platform:clean']
    environment:
      <<: *env
    <<: *common

  platform-seed:
    profiles:
      - platform-seed
    entrypoint: ['bash', '-c', 'npm run platform:seed']
    environment:
      <<: *env
    <<: *common

  platform-raise:
    profiles:
      - platform-raise
    entrypoint: ['bash', '-c', 'npm run platform:raise']
    environment:
      <<: *env
    <<: *common

networks:
  localnet:
    driver: bridge
    name: wenex-network
