version: '3.8'

x-common: &common
  build:
    context: .
  env_file:
    - .env
  networks:
    - client

services:
  #######################
  # CLIENT SERVICES
  #######################
  client:
    build:
      args:
        SERVICE_NAME: gateway
    ports:
      - '3000:3000' # REST
    environment:
      PORT: 3000
      NODE_ENV: prod
    <<: *common

  #######################
  # CRAFTS SERVICES
  #######################
  crafts:
    build:
      args:
        SERVICE_NAME: services
    ports:
      - '3001:3001' # REST
    environment:
      PORT: 3001
      NODE_ENV: prod
    <<: *common

networks:
  client:
    driver: bridge
