services:
  redis:
    container_name: redis
    image: redis/redis-stack:7.4.0-v2
    command: redis-server /etc/redis/redis.conf
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - ./config/redis.conf:/etc/redis/redis.conf
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
    name: wenex-network
