services:
  redis:
    container_name: redis
    image: redis/redis-stack:7.4.0-v2
    ports:
      - 6379:6379
      - 8001:8001
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
    name: wenex-network
