services:
  #######################
  # BROKER
  #######################

  nats:
    extends:
      file: docker-compose.nat.yml
      service: nats

  nats-1:
    extends:
      file: docker-compose.nat.yml
      service: nats-1

  nats-2:
    extends:
      file: docker-compose.nat.yml
      service: nats-2

networks:
  localnet:
    driver: bridge
    name: wenex-network
