services:
  nats:
    image: nats:2.11-alpine
    container_name: nats
    ports:
      - '4222:4222'
      - '8222:8222'
    command: '--server_name nats --cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 --routes=nats://nats1:6222,nats://nats2:6222 -js'
    networks:
      - localnet

  nats-1:
    image: nats:2.11-alpine
    container_name: nats1
    command: '--server_name nats1 --cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://nats:6222 -js'
    depends_on:
      - nats
    networks:
      - localnet

  nats-2:
    image: nats:2.11-alpine
    container_name: nats2
    command: '--server_name nats2 --cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://nats:6222 -js'
    depends_on:
      - nats
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
    name: wenex-network
